# Generated by Django 2.2.3 on 2019-10-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumenty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='short_name_device_own',
        ),
        migrations.AddField(
            model_name='device',
            name='type_name',
            field=models.ManyToManyField(help_text='Select a device type', to='dokumenty.DeviceType'),
        ),
    ]
