# Generated by Django 2.2.3 on 2019-10-06 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dokumenty', '0002_auto_20191006_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='short_name_device_own',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devicetype_device', to='dokumenty.DeviceType'),
        ),
    ]
