# Generated by Django 2.2.3 on 2019-10-06 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dokumenty', '0003_device_short_name_device_own'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='short_name_device_own',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_type_device', to='dokumenty.DeviceType'),
        ),
    ]
