# Generated by Django 2.2.3 on 2019-10-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumenty', '0004_auto_20191006_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crashreport',
            name='which_shift',
            field=models.CharField(blank=True, choices=[('I', 'Zmiana I (6:00 - 14:00)'), ('II', 'Zmiana II (14:00 - 22:00)'), ('III', 'Zmiana III (22:00 - 06:00)')], default='I', help_text='Zmiana.', max_length=100),
        ),
    ]
