# Generated by Django 2.2.3 on 2019-10-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumenty', '0006_auto_20191008_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('number_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_notice', models.DateField()),
                ('which_shift', models.CharField(blank=True, choices=[('I', 'Zmiana I (6:00 - 14:00)'), ('II', 'Zmiana II (14:00 - 22:00)'), ('III', 'Zmiana III (22:00 - 06:00)')], default='I', help_text='Zmiana.', max_length=3)),
                ('description', models.TextField(help_text='Please type what happened', max_length=1000)),
                ('status_notice', models.CharField(blank=True, choices=[('o', 'Otwarty'), ('p', 'Przetwarzanie'), ('z', 'Zakonczony')], default='o', help_text='Status dokumentu.', max_length=1)),
                ('which_stuff', models.ManyToManyField(help_text='Select a exactly devices', to='dokumenty.Device')),
                ('who_notice', models.ManyToManyField(help_text='Select a occupation for this employee', to='dokumenty.Author')),
            ],
        ),
    ]
