# Generated by Django 2.2.3 on 2019-10-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokumenty', '0009_usedparts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsedParts',
            new_name='UsedPart',
        ),
    ]
