# Generated by Django 2.2.3 on 2019-10-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumenty', '0010_auto_20191017_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereport',
            name='used_parts',
            field=models.ManyToManyField(help_text='Select used parts', to='dokumenty.UsedPart'),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='which_stuff',
            field=models.ManyToManyField(help_text='Select exactly devices', to='dokumenty.Device'),
        ),
    ]
